# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b1d6d1e7a96788affd8cd8c1ddd4e89e52c574ded73383638306a586a04d1858a6306d014f56994bd0acdc627a7271ece898a7d771bc85e791923f2b26a2e89

test:
  secret_key_base: 609ce2363349fa25f5bb410df6980a99dc6be29225e84669cd9557bc0b7c41375df733623bd5ab40d2cf73b6dfc5ea17a1fa3ab3bc370f1bf6b06cbb58563933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
